resilience4j:
  ratelimiter:
    configs:
      default:
        limitForPeriod: 3
        limitRefreshPeriod: 5s
        timeoutDuration: 0
    instances:
      myRateLimiter:
        baseConfig: default

